"""Extract joker metadata from Balatro's game.lua into a static Python registry.

One-off: run when the game updates or a new joker is added. Output goes to
src/balatro_bot/joker_registry.py.
"""
from __future__ import annotations

import re
from pathlib import Path

GAME_LUA = Path(r"C:\Users\Tyler\AppData\Roaming\Balatro\Mods\lovely\game-dump\game.lua")
OUT = Path(__file__).parent.parent / "src" / "balatro_bot" / "joker_registry.py"

LINE_RE = re.compile(r"^\s*(j_[a-z0-9_]+)\s*=\s*\{(.*)\}\s*,?\s*$")
RARITY_RE = re.compile(r"\brarity\s*=\s*(\d+)")
COST_RE = re.compile(r"\bcost\s*=\s*(\d+)")
NAME_RE = re.compile(r'\bname\s*=\s*"([^"]+)"')
EFFECT_RE = re.compile(r'\beffect\s*=\s*"([^"]*)"')

RARITY_LABEL = {1: "Common", 2: "Uncommon", 3: "Rare", 4: "Legendary"}


def main() -> None:
    text = GAME_LUA.read_text(encoding="utf-8")
    jokers: list[dict] = []
    for raw in text.splitlines():
        m = LINE_RE.match(raw)
        if not m:
            continue
        key, body = m.group(1), m.group(2)
        rarity = RARITY_RE.search(body)
        cost = COST_RE.search(body)
        name = NAME_RE.search(body)
        effect = EFFECT_RE.search(body)
        if not (rarity and cost and name):
            continue
        jokers.append({
            "key": key,
            "name": name.group(1),
            "rarity": int(rarity.group(1)),
            "cost": int(cost.group(1)),
            "effect_hint": effect.group(1) if effect else "",
        })
    jokers.sort(key=lambda j: (j["rarity"], j["cost"], j["key"]))

    lines = [
        '"""Static joker registry — extracted from Balatro game.lua.',
        "",
        "Auto-generated by scripts/extract_jokers.py. Do not edit by hand.",
        'Regenerate when the game updates."""',
        "",
        "from __future__ import annotations",
        "",
        "RARITY_LABEL = {1: \"Common\", 2: \"Uncommon\", 3: \"Rare\", 4: \"Legendary\"}",
        "",
        "JOKERS: list[dict] = [",
    ]
    for j in jokers:
        lines.append(
            f'    {{"key": {j["key"]!r}, "name": {j["name"]!r}, '
            f'"rarity": {j["rarity"]}, "cost": {j["cost"]}, '
            f'"effect_hint": {j["effect_hint"]!r}}},'
        )
    lines.append("]")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(jokers)} jokers to {OUT}")


if __name__ == "__main__":
    main()
